name: Submit to Baidu

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: cd blog && hugo

      - name: Submit
        run: |
          cp blog/public/zh-cn/sitemap.xml scripts
          cd scripts
          pip3 install lxml
          python3 baidu.py sitemap.xml "${{ secrets.BAIDU_API_URL }}"
          rm sitemap.xml
          cp blog/public/en/sitemap.xml scripts
          python3 baidu.py sitemap.xml "${{ secrets.BAIDU_API_URL }}"